# frozen_string_literal: true

RSpec.describe Keycloak::Service do
  let!(:private_key)  { OpenSSL::PKey::RSA.generate(2048) }
  let!(:public_key)   { private_key.public_key }
  let!(:key_resolver)  { Keycloak::PublicKeyCachedResolverStub.new(public_key) }
  let!(:service)       { Keycloak::Service.new(key_resolver) }

  before(:each) do
    now = Time.local(2018, 1, 9, 12, 0, 0)
    Timecop.freeze(now)
  end

  after(:each) do
    Timecop.return
  end

  describe '#decode_and_verify' do
    def create_token(private_key, expiration_date, algorithm, kid = nil)
      claim = {
        iss: 'Keycloak',
        exp: expiration_date.to_i,
        nbf: Time.local(2018, 1, 1, 0, 0, 0).to_i
      }
      header = {}
      header[:kid] = kid if kid
      JWT.encode(claim, private_key, algorithm.to_s, header)
    end

    context 'when token is nil' do
      let(:token) { nil }
      it 'should raise an error :no_token' do
        expect do
          service.decode_and_verify(token)
        end.to raise_error(TokenError, 'No JWT token provided')
      end
    end

    context 'when token is an empty string' do
      let(:token) { '' }
      it 'should raise an error :no_token' do
        expect do
          service.decode_and_verify(token)
        end.to raise_error(TokenError, 'No JWT token provided')
      end
    end

    context 'when token is in an invalid format' do
      let(:token) { 'coucou' }
      it 'should raise an error :invalid_format' do
        expect do
          service.decode_and_verify(token)
        end.to raise_error(TokenError, 'Wrong JWT Format')
      end
    end

    context 'when token is in a valid format' do
      let(:algorithm)       { :RS256 }
      let(:expiration_date) { Time.now + (7 * 24 * 60 * 60) } # 1 week from now

      context 'and token is generated by another private key' do
        let(:another_private_key)  { OpenSSL::PKey::RSA.generate(1024) }
        let(:token)                { create_token(another_private_key, expiration_date, algorithm) }

        it 'should raise an error :verification_failed' do
          expect do
            service.decode_and_verify(token)
          end.to raise_error(TokenError, 'Failed to verify JWT token')
        end
      end

      context 'and token is generated by the right private key' do
        let(:token) { create_token(private_key, expiration_date, algorithm) }

        context 'and token is expired' do
          let(:expiration_date) { Time.now - (2 * 24 * 60 * 60) } # 2 days ago

          it 'should raise an error :expiration_date' do
            expect do
              service.decode_and_verify(token)
            end.to raise_error(TokenError, 'JWT token is expired')
          end
        end

        context 'and token is not expired' do
          let(:expiration_date) { Time.now + (2 * 24 * 60 * 60) } # 2 days from now

          context 'and token is encrypted using RS256' do
            let(:algorithm) { :RS256 }

            it 'should return a not-nil decoded token' do
              expect(service.decode_and_verify(token)).to_not be_nil
            end
          end

          context 'and token is encrypted using RS512' do
            let(:algorithm) { :RS512 }

            it 'should return a not-nil decoded token' do
              expect(service.decode_and_verify(token)).to_not be_nil
            end
          end
        end
      end

      context 'when using JWK set (like Keycloak)' do
        let(:jwk) { JWT::JWK.new(private_key, kid: 'test-key-id', use: 'sig') }
        let(:jwk_set) { JWT::JWK::Set.new(jwk) }
        let(:jwk_resolver) { double('jwk_resolver', find_public_keys: jwk_set) }
        let(:jwk_service) { Keycloak::Service.new(jwk_resolver) }
        let(:token_with_kid) { create_token(private_key, expiration_date, algorithm, 'test-key-id') }
        let(:token_without_kid) { create_token(private_key, expiration_date, algorithm) }

        it 'should successfully decode token with matching kid' do
          result = jwk_service.decode_and_verify(token_with_kid)
          expect(result).to_not be_nil
          expect(result['iss']).to eq('Keycloak')
        end

        it 'should successfully decode token without kid (uses first key)' do
          result = jwk_service.decode_and_verify(token_without_kid)
          expect(result).to_not be_nil
          expect(result['iss']).to eq('Keycloak')
        end

        it "should raise error when kid doesn't match any key" do
          token_with_wrong_kid = create_token(private_key, expiration_date, algorithm, 'wrong-key-id')
          expect do
            jwk_service.decode_and_verify(token_with_wrong_kid)
          end.to raise_error(TokenError, 'Wrong JWT Format')
        end
      end
    end
  end

  describe '#read_token' do
    let(:query_string)       { '' }
    let(:url)                { "http://api.service.com/api/health?aParameter=true#{query_string}" }
    let(:headers)            { {} }
    let(:header_token)       { 'header_token' }
    let(:query_string_token) { 'query_string_token' }

    before(:each) do
      @token = service.read_token(url, headers)
    end

    context 'when the token is provided in the Authorization headers' do
      let(:headers) do
        {
          'HTTP_AUTHORIZATION' => "Bearer #{header_token}"
        }
      end
      context 'and not in the query string' do
        let(:query_string) { '' }
        it 'returns the header token' do
          expect(@token).to eq header_token
        end
      end

      context 'and also in the query string' do
        let(:query_string) { "&authorizationToken=#{query_string_token}" }
        it 'returns the query string token' do
          expect(@token).to eq query_string_token
        end
      end
    end

    context 'when the token is not provided in the Authorization headers' do
      let(:headers) do
        {
          'ANOTHER_HEADER' => header_token
        }
      end

      context 'and not in the query string' do
        let(:query_string) { '' }
        it 'returns an empty token' do
          expect(@token).to eq ''
        end
      end

      context 'and query string is nil' do
        let(:query_string) { nil }
        it 'returns an empty token' do
          expect(@token).to eq ''
        end
      end

      context 'but in the query string' do
        let(:query_string) { "&authorizationToken=#{query_string_token}" }
        it 'returns the query string token' do
          expect(@token).to eq query_string_token
        end
      end
    end
  end
end
